from django.db import models

# Create your models here.
class NestGuardDashboradPage(models.Model):
    titulo1 = models.TextField(blank=True, null=True)
    titulo2 = models.TextField(blank=True, null=True)
    titulo3 = models.TextField(blank=True, null=True)
    titulo4 = models.TextField(blank=True, null=True)
    titulo5 = models.TextField(blank=True, null=True)
    titulo6 = models.TextField(blank=True, null=True)
    titulo7 = models.TextField(blank=True, null=True)
    titulo8 = models.TextField(blank=True, null=True)
    titulo9 = models.TextField(blank=True, null=True)
    titulo10 = models.TextField(blank=True, null=True)
    titulo11 = models.TextField(blank=True, null=True)
    titulo12 = models.TextField(blank=True, null=True)
    titulo13 = models.TextField(blank=True, null=True)
    titulo14 = models.TextField(blank=True, null=True)
    descricao1 = models.TextField(blank=True, null=True)
    descricao2 = models.TextField(blank=True, null=True)
    descricao3 = models.TextField(blank=True, null=True)
    descricao4 = models.TextField(blank=True, null=True)
    descricao5 = models.TextField(blank=True, null=True)
    descricao6 = models.TextField(blank=True, null=True)
    descricao7 = models.TextField(blank=True, null=True)
    descricao8 = models.TextField(blank=True, null=True)
    descricao9 = models.TextField(blank=True, null=True)
    descricao10 = models.TextField(blank=True, null=True)
    descricao11 = models.TextField(blank=True, null=True)
    descricao12 = models.TextField(blank=True, null=True)
    descricao13 = models.TextField(blank=True, null=True)
    descricao14 = models.TextField(blank=True, null=True)
    imagem1 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem2 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem3 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem4 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem5 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem6 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem7 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem8 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem9 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem10 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem11 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem12 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem13 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem14 = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.titulo1
    
class NestGuardSitesPage(models.Model):
    titulo1 = models.TextField(blank=True, null=True)
    titulo2 = models.TextField(blank=True, null=True)
    titulo3 = models.TextField(blank=True, null=True)
    titulo4 = models.TextField(blank=True, null=True)
    titulo5 = models.TextField(blank=True, null=True)
    titulo6 = models.TextField(blank=True, null=True)
    titulo7 = models.TextField(blank=True, null=True)
    titulo8 = models.TextField(blank=True, null=True)
    titulo9 = models.TextField(blank=True, null=True)
    titulo10 = models.TextField(blank=True, null=True)
    titulo11 = models.TextField(blank=True, null=True)
    titulo12 = models.TextField(blank=True, null=True)
    titulo13 = models.TextField(blank=True, null=True)
    titulo14 = models.TextField(blank=True, null=True)
    descricao1 = models.TextField(blank=True, null=True)
    descricao2 = models.TextField(blank=True, null=True)
    descricao3 = models.TextField(blank=True, null=True)
    descricao4 = models.TextField(blank=True, null=True)
    descricao5 = models.TextField(blank=True, null=True)
    descricao6 = models.TextField(blank=True, null=True)
    descricao7 = models.TextField(blank=True, null=True)
    descricao8 = models.TextField(blank=True, null=True)
    descricao9 = models.TextField(blank=True, null=True)
    descricao10 = models.TextField(blank=True, null=True)
    descricao11 = models.TextField(blank=True, null=True)
    descricao12 = models.TextField(blank=True, null=True)
    descricao13 = models.TextField(blank=True, null=True)
    descricao14 = models.TextField(blank=True, null=True)
    imagem1 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem2 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem3 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem4 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem5 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem6 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem7 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem8 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem9 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem10 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem11 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem12 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem13 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem14 = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.titulo1


class NestGuardSegurançaPage(models.Model):
    titulo1 = models.TextField(blank=True, null=True)
    titulo2 = models.TextField(blank=True, null=True)
    titulo3 = models.TextField(blank=True, null=True)
    titulo4 = models.TextField(blank=True, null=True)
    titulo5 = models.TextField(blank=True, null=True)
    titulo6 = models.TextField(blank=True, null=True)
    titulo7 = models.TextField(blank=True, null=True)
    titulo8 = models.TextField(blank=True, null=True)
    titulo9 = models.TextField(blank=True, null=True)
    titulo10 = models.TextField(blank=True, null=True)
    titulo11 = models.TextField(blank=True, null=True)
    titulo12 = models.TextField(blank=True, null=True)
    titulo13 = models.TextField(blank=True, null=True)
    titulo14 = models.TextField(blank=True, null=True)
    descricao1 = models.TextField(blank=True, null=True)
    descricao2 = models.TextField(blank=True, null=True)
    descricao3 = models.TextField(blank=True, null=True)
    descricao4 = models.TextField(blank=True, null=True)
    descricao5 = models.TextField(blank=True, null=True)
    descricao6 = models.TextField(blank=True, null=True)
    descricao7 = models.TextField(blank=True, null=True)
    descricao8 = models.TextField(blank=True, null=True)
    descricao9 = models.TextField(blank=True, null=True)
    descricao10 = models.TextField(blank=True, null=True)
    descricao11 = models.TextField(blank=True, null=True)
    descricao12 = models.TextField(blank=True, null=True)
    descricao13 = models.TextField(blank=True, null=True)
    descricao14 = models.TextField(blank=True, null=True)
    imagem1 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem2 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem3 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem4 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem5 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem6 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem7 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem8 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem9 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem10 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem11 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem12 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem13 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem14 = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.titulo1
    
class NestGuardContatoPage(models.Model):
    titulo1 = models.TextField(blank=True, null=True)
    titulo2 = models.TextField(blank=True, null=True)
    titulo3 = models.TextField(blank=True, null=True)
    titulo4 = models.TextField(blank=True, null=True)
    titulo5 = models.TextField(blank=True, null=True)
    titulo6 = models.TextField(blank=True, null=True)
    titulo7 = models.TextField(blank=True, null=True)
    titulo8 = models.TextField(blank=True, null=True)
    titulo9 = models.TextField(blank=True, null=True)
    titulo10 = models.TextField(blank=True, null=True)
    titulo11 = models.TextField(blank=True, null=True)
    titulo12 = models.TextField(blank=True, null=True)
    titulo13 = models.TextField(blank=True, null=True)
    titulo14 = models.TextField(blank=True, null=True)
    descricao1 = models.TextField(blank=True, null=True)
    descricao2 = models.TextField(blank=True, null=True)
    descricao3 = models.TextField(blank=True, null=True)
    descricao4 = models.TextField(blank=True, null=True)
    descricao5 = models.TextField(blank=True, null=True)
    descricao6 = models.TextField(blank=True, null=True)
    descricao7 = models.TextField(blank=True, null=True)
    descricao8 = models.TextField(blank=True, null=True)
    descricao9 = models.TextField(blank=True, null=True)
    descricao10 = models.TextField(blank=True, null=True)
    descricao11 = models.TextField(blank=True, null=True)
    descricao12 = models.TextField(blank=True, null=True)
    descricao13 = models.TextField(blank=True, null=True)
    descricao14 = models.TextField(blank=True, null=True)
    imagem1 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem2 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem3 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem4 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem5 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem6 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem7 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem8 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem9 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem10 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem11 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem12 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem13 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem14 = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.titulo1
    
class NestGuardSobrePage(models.Model):
    titulo1 = models.TextField(blank=True, null=True)
    titulo2 = models.TextField(blank=True, null=True)
    titulo3 = models.TextField(blank=True, null=True)
    titulo4 = models.TextField(blank=True, null=True)
    titulo5 = models.TextField(blank=True, null=True)
    titulo6 = models.TextField(blank=True, null=True)
    titulo7 = models.TextField(blank=True, null=True)
    titulo8 = models.TextField(blank=True, null=True)
    titulo9 = models.TextField(blank=True, null=True)
    titulo10 = models.TextField(blank=True, null=True)
    titulo11 = models.TextField(blank=True, null=True)
    titulo12 = models.TextField(blank=True, null=True)
    titulo13 = models.TextField(blank=True, null=True)
    titulo14 = models.TextField(blank=True, null=True)
    descricao1 = models.TextField(blank=True, null=True)
    descricao2 = models.TextField(blank=True, null=True)
    descricao3 = models.TextField(blank=True, null=True)
    descricao4 = models.TextField(blank=True, null=True)
    descricao5 = models.TextField(blank=True, null=True)
    descricao6 = models.TextField(blank=True, null=True)
    descricao7 = models.TextField(blank=True, null=True)
    descricao8 = models.TextField(blank=True, null=True)
    descricao9 = models.TextField(blank=True, null=True)
    descricao10 = models.TextField(blank=True, null=True)
    descricao11 = models.TextField(blank=True, null=True)
    descricao12 = models.TextField(blank=True, null=True)
    descricao13 = models.TextField(blank=True, null=True)
    descricao14 = models.TextField(blank=True, null=True)
    imagem1 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem2 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem3 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem4 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem5 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem6 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem7 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem8 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem9 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem10 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem11 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem12 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem13 = models.ImageField(upload_to='images/', blank=True, null=True)
    imagem14 = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.titulo1
    
class NestGuardCard(models.Model):
    titulo = models.TextField(blank=True, null=True)
    descricao = models.TextField(blank=True, null=True)
    link_img = models.URLField(blank=True, null=True)
    descricaoModal = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.titulo